server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/image_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 自定义配置
app:
  storage-path: D:/data/images/original/  # 原图存储路径
  thumbnail-path: D:/data/images/thumbs/  # 缩略图存储路径
  jwt-secret: 123456         # JWT密钥